# version: '3.9'

services:
  db:
    image: postgres:16.9
    env_file:
      - .env
    # Подключаем скрипт инициализации
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"

  web:
    build: .
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8000:8000"
